name: Java CI with Maven using Trigger

on:
  push:
    branches: [ "disabled" ]

  workflow_dispatch:

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Jenkins Job
      run: |
        curl -I -X POST "https://192.168.1.193:8080/job/TomcatDeployment/build" --user "qasachin:${{ secrets.JENKINS_TOKEN }}"

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
