name: Java CI with Maven using Trigger

on:
  push:
    branches: [ "disabled" ]

  workflow_dispatch:

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:        
    - id: triggerjenkinsjob
      uses: mickeygoussetorg/trigger-jenkins-job@v1
      with:
        jenkins-server:  "http://192.168.1.193:8080"
        jenkins-job: "TomcatDeployment"
        jenkins-username: qasachin
        jenkins-pat: ${{ secrets.JENKINS_TOKEN }}
        poll-time: 10
        timeout-value: 600
        verbose: true
