name: Build and Deploy Java Web App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Upload WAR file
        run: ls -l

      - name: Deploy WAR to Apache Tomcat via SSH
        uses: appleboy/scp-action@master
        with:
          host: "http://localhost:8081/"
          username: ${{ secrets.TOMCAT_USER }}
          password: ${{ secrets.TOMCAT_PASSWORD }}
          source: "./target/*.war"
          target: "/webapps/"