name: Build and Deploy Java Web App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test

      - name: Upload WAR file
        run: ls -lart ./target

      - name: Upload Artifact
        if: success()  # Only execute if previous steps were successful
        uses: actions/upload-artifact@v4
        with:
          name: welcome-app-war
          path: "*/*.war"
          if-no-files-found: error

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: welcome-app-war
          path: "/home/runner/work/github-jenkins-end-project/github-jenkins-end-project/target/"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.TOMCAT_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to Tomcat
        run: |
              scp -i "~/.ssh/id_rsa" -o StrictHostKeyChecking=no /home/runner/work/github-jenkins-end-project/github-jenkins-end-project/target/welcome-app.war ${{ secrets.TOMCAT_USER }}@${{ secrets.TOMCAT_HOST }}:/opt/tomcat/webapps